### ISSUE TITLE
KITTI-MOTS, MOTS 2020 Dataset and pretrained models

### ISSUE THREAD

**Issue by trqminh** [AnwesaChoudhuri/CAROQ#1]
Thank you for your publish code of your interesting work!
I'd like to know when will you add the tracking datasets registration and instruction (e.g. KITTI-MOTS, MOTS 2020). Or it would be great if you could give me some reference to where I can set it up.

Thank you for your consideration

**Comment by AnwesaChoudhuri** [comment]
> Thank you for your publish code of your interesting work! I'd like to know when will you add the tracking datasets registration and instruction (e.g. KITTI-MOTS, MOTS 2020). Or it would be great if you could give me some reference to where I can set it up.
> 
> Thank you for your consideration

Hi, 
Thank you for your interest in our work! The KITTI-MOTS and MOTS-2020 datasets are now added. Please follow [here](https://github.com/AnwesaChoudhuri/CAROQ/tree/master/datasets).
